# Generated by Django 2.0.9 on 2018-11-09 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruban', '0002_product_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bid_value',
            field=models.IntegerField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
